name: tests
on: [push, pull_request]
jobs:
  test:
    name: "Run all tests on ${{ matrix.jvm_version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jvm_version: [adopt@1.11, openjdk@1.14, graalvm@]
        os: [ubuntu-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier/v1
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

  
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: ${{ matrix.jvm_version }}
    - name: Compile
      run: sbt test



